//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Рисовалка
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImages
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime Created { get; set; }
        public string Status { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
